//Cursos
export const ADD_NEW_COURSE_REQUEST = "ADD_NEW_COURSE_REQUEST";
export const ADD_NEW_COURSE_SUCCESS = "ADD_NEW_COURSE_SUCCESS";
export const REMOVE_COURSE_REQUEST = "REMOVE_COURSE_REQUEST";
export const REMOVE_COURSE_SUCCESS = "REMOVE_COURSE_SUCCESS";
export const GET_ALL_COURSE_REQUEST = "GET_ALL_COURSE_REQUEST";
export const GET_ALL_COURSE_SUCCESS = "GET_ALL_COURSE_SUCCESS";

//Usuarios
export const ADD_NEW_USER_REQUEST = "ADD_NEW_USER_REQUEST";
export const ADD_NEW_USER_SUCCESS = "ADD_NEW_USER_SUCCESS";
export const GET_ALL_USER_REQUEST = "GET_ALL_USER_REQUEST";
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";