export const ADD_NEW_COURSE_REQUEST = "ADD_NEW_COURSE_REQUEST";
export const ADD_NEW_COURSE_SUCCESS = "ADD_NEW_COURSE_SUCCESS";
export const REMOVE_COURSE_REQUEST = "REMOVE_COURSE_REQUEST";
export const REMOVE_COURSE_SUCCESS = "REMOVE_COURSE_SUCCESS";
export const GET_ALL_COURSE_REQUEST = "GET_ALL_COURSE_REQUEST";
export const GET_ALL_COURSE_SUCCESS = "GET_ALL_COURSE_SUCCESS";